const closes=[1.1722,1.1724,1.1726,1.1727,1.1729,1.1730,1.1731,1.1733,1.1734,1.1735,1.1736,1.1738];
const forecasts=[];
function baseline(x){const a=(x.at(-1)-x.at(-4))/x.at(-4),b=(x.at(-1)-x.at(-10))/x.at(-10),score=.6*a+.4*b;return{direction:score>.00015?"UP":score<-.00015?"DOWN":"FLAT",confidence:Math.min(.97,.5+Math.abs(score)*1800),regime:Math.abs(b)>.001?(b>0?"TREND_UP":"TREND_DOWN"):Math.abs(b)<.00025?"RANGE":"VOLATILE"}}
function tick(){document.querySelector("#clock").textContent=new Date().toISOString().slice(11,19)+" UTC"}setInterval(tick,1000);tick();
function draw(){const c=document.querySelector("#chart"),x=c.getContext("2d"),lo=Math.min(...closes),hi=Math.max(...closes);x.clearRect(0,0,c.width,c.height);x.strokeStyle="#5eead4";x.lineWidth=2;x.beginPath();closes.forEach((v,i)=>{const px=i*(c.width-40)/(closes.length-1)+20,py=c.height-20-(v-lo)/(hi-lo)*(c.height-40);i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke()}draw();
function addForecast(){const f=baseline(closes),now=new Date(),end=new Date(now.getTime()+300000),id="p-"+String(forecasts.length+1).padStart(3,"0");forecasts.unshift({id,now,end,f});document.querySelector("#dir").textContent=f.direction;document.querySelector("#conf").textContent=(f.confidence*100).toFixed(1)+"%";document.querySelector("#reg").textContent=f.regime;renderRows()}
function renderRows(){const body=document.querySelector("#rows");body.innerHTML=forecasts.map(o=>"<tr><td class='mono'>"+o.id+"</td><td>"+o.now.toISOString()+"</td><td>"+o.end.toISOString()+"</td><td>"+o.f.direction+"</td><td>"+(o.f.confidence*100).toFixed(1)+"%</td><td class='yellow'>AWAITING REALITY</td></tr>").join("")||"<tr><td colspan='6' class='muted'>No forecasts locked in this browser session.</td></tr>"}
document.querySelector("#go").onclick=addForecast;renderRows();
document.querySelectorAll(".nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".nav button").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelector("#"+b.dataset.view).classList.add("active")});
document.querySelector("#n").textContent="0";document.querySelector("#mae").textContent="—";document.querySelector("#net").textContent="—";